# Create Terraform Cloud Variable Set for Azure credentials
resource "tfe_variable_set" "azure_credentials" {
  name         = "Azure Workload Identity Credentials"
  description  = "Azure credentials for workload identity federation - auto-generated by bootstrap"
  organization = var.tfc_organization
  global       = true # Apply to all workspaces in the organization
}

# Add environment variables to the variable set
resource "tfe_variable" "tfc_azure_provider_auth" {
  key             = "TFC_AZURE_PROVIDER_AUTH"
  value           = "true"
  category        = "env"
  description     = "Enable Azure provider authentication via workload identity"
  variable_set_id = tfe_variable_set.azure_credentials.id
}

resource "tfe_variable" "tfc_azure_run_client_id" {
  key             = "TFC_AZURE_RUN_CLIENT_ID"
  value           = azuread_application.tfc.client_id
  category        = "env"
  description     = "Azure AD Application (client) ID for workload identity"
  variable_set_id = tfe_variable_set.azure_credentials.id
}

resource "tfe_variable" "arm_subscription_id" {
  key             = "ARM_SUBSCRIPTION_ID"
  value           = data.azurerm_subscription.current.subscription_id
  category        = "env"
  description     = "Azure Subscription ID"
  variable_set_id = tfe_variable_set.azure_credentials.id
}

resource "tfe_variable" "arm_tenant_id" {
  key             = "ARM_TENANT_ID"
  value           = data.azurerm_client_config.current.tenant_id
  category        = "env"
  description     = "Azure Tenant ID"
  variable_set_id = tfe_variable_set.azure_credentials.id
}