name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build binaries
        working-directory: ./bootstrap/setup-azure-workload-identity
        run: |
          chmod +x build.sh
          VERSION=${{ steps.version.outputs.VERSION }} ./build.sh

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bootstrap/setup-azure-workload-identity/bin/*.tar.gz
            bootstrap/setup-azure-workload-identity/bin/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ steps.version.outputs.VERSION }}
          path: |
            bootstrap/setup-azure-workload-identity/bin/*.tar.gz
            bootstrap/setup-azure-workload-identity/bin/*.zip
